server:
  port: 8085
spring:  
  main:
    allow-bean-definition-overriding: true     
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  profiles:
    active: local    
okta:
  oauth2:
    issuer: https://dev-164193.oktapreview.com/oauth2/default
    client-id: 0oanfv2pxqhKziDNf0h7
    client-secret: bRt34-fdJd7YXeYEWTyjNxMsl3Nedmjn3-Pi7Xtb
    roles-claim: groups
    scopes:
    - openid   
    - profile
---  
spring:
  profiles: local  
  datasource:
    url: jdbc:mysql://localhost:3306/bootjpa
    username: root
    password: password
    driver-class-name: "com.mysql.jdbc.Driver"
---
spring:
  profiles: remote     
  datasource:
    url: jdbc:mysql://database-1.cvjtnk6zxahm.us-east-1.rds.amazonaws.com/bootjpa
    username: admin
    password: rootpassword
    driver-class-name: "com.mysql.jdbc.Driver"